### ISSUE TITLE
Access the Proxy Dashboard 

### ISSUE THREAD

**Issue by pivotal-carlos-vasquez** [pivotal-cf/docs-mysql-pas#4]
I wanted to suggest an update to this document. There is a login required to see the proxy dashboard and the way to get credentials for this login is to use this url: https://<OpsManagerURL>/api/v0/deployed/products/<PAS/ERT deployment>/variables?name=mysql-proxy-dashboard-credentials

**Comment by mjgutermuth** [comment]
Hi @pivotal-carlos-vasquez, thank you for this! Unfortunately, I can't see which topic you're referring to. Would you be able to provide a link? Thanks!

**Comment by mjgutermuth** [comment]
Just to follow up--it looks like this has been updated now: https://docs.pivotal.io/application-service/2-10/mysql/bootstrap-mysql.html#proxy-dashboard-login

Thanks for pointing this out!
